### PR TITLE
Pico device

### PR DESCRIPTION
**Pull request by jantrautmann**
I implemented the funny python things we discussed.

How can I check what causes that it cannot automatically merge?

Should we discuss about the server in the near future or should I continue adding methods for the picoscope?

### CODE REVIEW

**Comment by jantrautmann** [comment]
Checking the conflict file, I do not get why automatic merge. Especially where I just added things.

**Comment by stepansnigirev** [comment]
Can you run `black` on your code? It may resolve most of the issues.

**Comment by jantrautmann** [comment]
I ran black, but still the same conflicts. Should I resolve them by hand?

**Comment by stepansnigirev** [comment]
Yeah, you can resolve from GitHub UI - probably makes sense to delete content from master and only keep stuff from your PR. You can just delete the whole content of the file and paste yours in the "Resolve conflicts" editor.
Makes sense to keep the branch up to date. You can do it either from command line, or GitHub UI via "sync fork" button.

**Comment by stepansnigirev** [comment]
Just resolved =)

**Pull request merged**
